apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-weather-app
  namespace: default
  labels:
    app: my-weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-weather-app
  template:
    metadata:
      labels:
        app: my-weather-app
    spec:
      containers:
      - name: my-weather-app
        image: asia-east1-docker.pkg.dev/dev-zephyr-352206/my-weather-app/my-weather-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openweather-api-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-weather-app-service
  namespace: default
spec:
  selector:
    app: my-weather-app
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
